### PR TITLE
Info helper

### PR DESCRIPTION
**Pull request by trc855**
A drop down helper to assist the user in using roots 🌱 🐝

### CODE REVIEW

**Review by Gurmukh300 — DISMISSED** [review]
Hey, the color looks odd and does not match the theme, and Placeholder does nothing.

info helper

**Comment by trc855** [comment]
Sub nav will receive a re-style before presentation, which is beyond the intended scope of this branch.

**Comment by cnandes** [comment]
Muted the colours slightly to be more on theme but can revise again on another branch. I think blue == info makes sense but open to other suggestions

image

**Review by cnandes — APPROVED** [review]
Thanks for making those changes - LGTM 😎

**Pull request merged**
